### ISSUE TITLE
Deleting activation  messages 

### ISSUE THREAD

**Issue by DanValnicek** [FajsiEx/tea-bot#16]
Make the bot delete activation message after doing action to prevent spam and ppl rewriting activation messages asuming that bot will react

**Comment by FajsiEx** [comment]
could you explain more what you mean by activation msg?
Do you mean `!ping` or the bot response?

**Comment by FajsiEx** [comment]
I think wym now...
Bot has checks for this (deletes the msg if a user is restricted) but we want to know who sent the msg most of the times...
I guess the most I could do is to erase msgs if they have wrong command but idk.
I'll think about this later...

**Comment by DanValnicek** [comment]
but always when bot sends response he pings user so we know who sent the activation message. And by activation message i mean everything that users types and starts with"!"

**Comment by FajsiEx** [comment]
Pinging the user is bad that's why I removed it in early versions of legacy... we could just write the name of the user that sent the command.
But I don't think this resolves your issue with people writing commands when the bot is not responding. If the bot is not responding, then it's down and therefore can't delete the request message. I have handled some cases by deleting the command message (like restriction) but I am thinking of deleting it on error and on invalid command. I think that are all the cases where the bot won't respond and beyond that is only the case where the bot can't do anything at all - means can't even delete the message.

**Comment by DanValnicek** [comment]
Yeah i'ts ok to just write users name even when pinging si ok because when you are typing command you are on discord anyway. But bot not responding thing i meant when you  type for example !nuke and bot will say how many and user will edit the original message and thinks  that bol will respond to changed query that he already fulfilled.

**Comment by FajsiEx** [comment]
![image](https://user-images.githubusercontent.com/32551223/58646184-2b893c00-8305-11e9-85ee-30821f31d0c4.png)
It does look a little odd and some commands will have to have more verbose response but let me know how you like the implementation for now. Personally I don't like it... but that might be because all of the responses are clusterfucked together...
As for your explanation of why: I have seen literally 0 people use commands like that (correct me if I'm wrong)

**Comment by DanValnicek** [comment]
yeah that is nice

**Comment by DanValnicek** [comment]
That thing  "by" means who created the command, and "caller" means who called ? Or it is the same thing?

**Comment by FajsiEx** [comment]
by is my name (as a bot creator)
caller is who typed the command.

**Comment by DanValnicek** [comment]
Yeah, that is what I thought.
